config/routes.rb
Rails.application.routes.draw do
  resources :sections do
    resources :topics
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/section.rb
class Section < ApplicationRecord
  validates :title, presence: true

  belongs_to :parent, class_name: 'Section', optional: true
  has_many :sub_sections, class_name: 'Section', foreign_key: 'parent_id'
  has_many :topics, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :section
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @container = false
    @sections = Section.where(parent_id: nil).order(:created_at).includes(:sub_sections, :topics)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]

  # GET /sections or /sections.json
  def index
    @sections = Section.where(parent_id: nil).order(:created_at).includes(:sub_sections)
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to sections_url, notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to section_url(@section), notice: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy!

    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:title, :parent_id)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]
  before_action :set_section, only: %i[ new show edit create update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = @section.topics.build(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to section_path(@section), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to section_path(@section), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy!

    respond_to do |format|
      format.html { redirect_to section_path(@section), notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def set_section
      @section = Section.find(params[:section_id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/home/_sub_section.html.erb
<li class="breaking mt-1">
  <%= link_to section.title, "#" + section.id.to_s , class: "text-blue-500 p-2 pr-8 inline-block hover:bg-gray-100 hover:underline"  %>

  <ul class="pl-8 section" style="list-style-type: circle;">
    <% section.sub_sections.each do |sub| %>
      <% if sub.sub_sections.any? %>
        <%= render partial: "home/sub_section", locals: { section: sub } %>
      <% else %>
        <li>
          <%= link_to sub.title, "#" + sub.id.to_s, class: "text-blue-500 hover:underline"  %>
        </li>
      <% end  %>
    <% end %>
  </ul>
</li>

app/views/home/_sub_topic.html.erb
<li class="mt-3">
  <h2 class="text-theme-red text-2xl" id="<%= section.id %>"> <%= section.title %> </h2>

  <ul class="pl-8 section list-disc">
    <% section.topics.each do |topic| %>
      <li class="mt-1">
        <div class="flex gap-2">
          <%= link_to topic.title, "#", class: "text-blue-500 hover:underline" %>

          <% if topic.video.present?  %>
            <%= link_to topic.video, target: "_blank", class: "border-b-2 border-transparent hover:border-theme-red text-theme-red opacity-60 hover:opacity-100 flex gap-1 text-sm items-center" do %>
              <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                <path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z"></path><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02"></polygon>
              </svg>
              Video
            <% end %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>

  <ul class="list-disc ml-8">
    <% section.sub_sections.each do |sub| %>
      <% if sub.topics.any? %>
        <%= render partial: "home/sub_topic", locals: { section: sub } %>
      <% end %>
    <% end %>
  </ul>
</li>

app/views/home/index.html.erb
<h2 class="text-theme-gray border-t-4 border-b-4 border-theme-gray py-3 text-center text-3xl header">Topic Order</h2>

<ul class="list-disc ml-3" style="column-count: 2;">
  <% @sections.each do |section| %>
    <%= render partial: "home/sub_section", locals: { section: section } %>
  <% end %>
</ul>

<hr class="my-6 h-[5px] bg-theme-red border-none" />

<ul class="mt-4 ml-3">
  <% @sections.each do |section| %>
    <%= render partial: "home/sub_topic", locals: { section: section } %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M01</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="bg-theme-red">
      <div class="h-[72px] flex items-center container px-5 mx-auto" style="max-width: 1200px;">
        <a href="/">
          <h1 class="text-white text-2xl text-center">Web m01</h1>
        </a>
      </div>
    </div>

    <header class="bg-theme-sky p-4">
      <div class="container flex justify-center px-5 mx-auto gap-10 text-sm font-medium" style="max-width: 1200px;">
        <%= link_to "Home", root_path, class: "hover:opacity-60" %>
        <%= link_to "About us", root_path, class: "hover:opacity-60" %>
        <%= link_to "Blog", root_path, class: "hover:opacity-60" %>
        <%= link_to "Sections", sections_path, class: "hover:opacity-60" %>
      </div>
    </header>

    <main class="container mx-auto mt-8 px-5" style="max-width: 1200px;">
      <%= yield %>
    </main>
  </body>
</html>

app/views/sections/_form.html.erb
<%= form_with(model: section, class: "contents") do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% if section.parent_id.nil? %>
    <%= form.hidden_field :parent_id, value: params[:parent_id] %>
  <% end  %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/sections/_section.html.erb
<div id="<%= dom_id section %>" class="my-5">
  <h2 class="font-bold text-2xl flex gap-2 items-center">
    <%= link_to section.title, section, class: "hover:underline" %>
    <%= link_to 'Add section',
      new_section_path(parent_id: section.id),
      class: "text-sm font-medium text-blue-600 dark:text-blue-500 hover:underline"
    %>
  </h2>

  <ul class="mt-2 pl-8" style="list-style-type: circle;">
    <% section.sub_sections.each do |sub| %>
      <%= render partial: "sections/sub_section", locals: { section: sub } %>
    <% end %>
  </ul>

  <div class="my-4 pl-5">
  </div>

  <% if action_name != "show" %>
    <div class="mt-4 text-sm">
      <%= link_to 'Edit this section', edit_section_path(section), class: "rounded-lg py-2 ml-2 px-4 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
    </div>
  <% end %>
</div>

app/views/sections/_sub_section.html.erb
<li>
  <div class="flex gap-2 items-center">
    <%= link_to section.title, section, class: "text-gray-500 hover:underline" %>

    <%= link_to 'Add section',
        new_section_path(parent_id: section.id),
        class: "text-xs font-medium text-blue-600 dark:text-blue-500 hover:underline"
      %>
  </div>

  <ul class="pl-8 section" style="list-style-type: circle;">
    <% section.sub_sections.each do |sub| %>
      <% if sub.sub_sections.any? %>
        <%= render partial: "sections/sub_section", locals: { section: sub } %>
      <% else %>
        <li>
          <div class="flex gap-2 items-center">
            <%= link_to sub.title, sub, class: "text-gray-500 hover:underline" %>
            <%= link_to 'Add section',
              new_section_path(parent_id: sub.id),
              class: "text-xs font-medium text-blue-600 dark:text-blue-500 hover:underline"
            %>
          </div>
        </li>
      <% end  %>
    <% end %>
  </ul>
</li>

app/views/sections/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing section</h1>

  <%= render "form", section: @section %>

  <%= link_to "Show this section", @section, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to sections", sections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sections/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Sections</h1>
    <%= link_to 'New section', new_section_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="sections" class="min-w-full">
    <%= render @sections %>
  </div>
</div>

app/views/sections/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New section</h1>

  <%= render "form", section: @section %>

  <%= link_to 'Back to sections', sections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sections/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @section %>

    <%= link_to 'Edit this section', edit_section_path(@section), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

    <div class="inline-block ml-2 mb-4">
      <%= button_to 'Destroy this section', section_path(@section), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>

    <%= link_to 'Back to sections', sections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

    <hr>

    <div class="flex justify-between items-center mt-4 mb-2">
      <h1 class="font-bold text-xl">Topics</h1>
      <%= link_to 'New topic', new_section_topic_path(@section), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>

    <% if @section.topics.any? %>
      <ul class="">
        <% @section.topics.each do |topic| %>
          <li class="flex items-center gap-2 py-1">
            <%= link_to "* " + topic.title, section_topic_path(@section, topic) %>
            <% if topic.video.present?  %>
              <%= link_to "🎥 video", topic.video, target: "_blank", class: "border-b-2 border-red-500" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>

  </div>
</div>

app/views/topics/_form.html.erb
<%= form_with(model: [section, topic], class: "contents") do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :video %>
    <%= form.text_field :video, pattern: "^https?://.+", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <small class="text-yellow-400">Please enter a valid URL video</small>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= topic.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Video:</strong>
    <%= topic.video %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Section:</strong>
    <%= topic.section_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this topic", topic, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this topic', edit_topic_path(topic), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/topics/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing topic</h1>

  <%= render "form", topic: @topic, section: @section %>

  <%= link_to "Show this topic", section_topic_path(@topic), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to 'Back to section', section_path(@section), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

</div>

app/views/topics/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Topics</h1>
  </div>

  <div id="topics" class="min-w-full">
  </div>
</div>

app/views/topics/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New topic</h1>

  <%= render "form", topic: @topic, section: @section %>

  <%= link_to 'Back to section', section_path(@section), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/topics/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @topic %>

    <%= link_to 'Edit this topic', edit_section_topic_path(@section, @topic), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this topic', section_topic_path(@section, @topic), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to topics', section_path(@section) , class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>